package com.d01.exception;



public class ExceptionMain05 {
	
	public static void main(String[] args) {
		System.out.println("=====예외가 발생하지않았을 경우=====");
		try {
			System.out.println("1");
			System.out.println("2");
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("3");
		
		}finally {//예외가 발생하건 않건 항사 수행됨
			System.out.println("4");
//			System.out.println();
		}
		System.out.println("프로그램 종료");
		System.out.println("----------------");
		
		System.out.println("===예외 ===");
		try {
			System.out.println("1");
			System.out.println(10/0);//예외 발생
			System.out.println("2");
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("4");
		}
		System.out.println("프로그램 종료");
	}

}
